version: '3.7'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: es1
    environment:
      - node.name=es1
    networks:
      - elastic
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es1:9200/
    ports:
      - 5601:5601
    networks:
      - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.2
    container_name: filebeat
    environment:
      - setup.kibana.host=kibana:5601

    ports:
      - 9000:9000
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logfile/:/mnt/log
    networks:
      - elastic

networks:
  elastic:

configs:
  filebeat_config:
    file: filebeat/filebeat.docker.yml
